name : Unite_test
on :
  push:
    branches :
      - main 
    pull:
      branches:
        - main
jobs :
    job1: 
        runs-on : ubuntu-latest
        steps :
          - name : Checkout repository
            uses : actions/checkout@v2

          - name : Install dependencies
            run : |
              python -m pip install --upgrade pip
              pip install unittest
          - name : Run tests
            run : |
              python -m unittest discover -s tests
